{{/*
Create a helper to detect if the chart is running on OpenShift.
*/}}
{{- define "universal-chart.isOpenShift" -}}
  {{- if.Capabilities.APIVersions.Has "route.openshift.io/v1" -}}
    {{- true -}}
  {{- end -}}
{{- end -}}

{{/*
Define other standard helpers like fullname, chart name, etc.
This is typically generated by `helm create`.
*/}}
{{- define "universal-chart.fullname" -}}
{{- if.Values.fullnameOverride }}
{{-.Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default.Chart.Name.Values.nameOverride }}
{{- if contains $name.Release.Name }}
{{-.Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s".Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{- define "universal-chart.name" -}}
{{- default.Chart.Name.Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "universal-chart.chart" -}}
{{- printf "%s-%s".Chart.Name.Chart.Version | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "universal-chart.labels" -}}
helm.sh/chart: {{ include "universal-chart.chart". }}
{{ include "universal-chart.selectorLabels". }}
{{- if.Chart.AppVersion }}
app.kubernetes.io/version: {{.Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{.Release.Service }}
{{- end }}

{{- define "universal-chart.selectorLabels" -}}
app.kubernetes.io/name: {{ include "universal-chart.name". }}
app.kubernetes.io/instance: {{.Release.Name }}
{{- end }}

{{- define "universal-chart.serviceAccountName" -}}
{{- if.Values.serviceAccount.create }}
{{- default (include "universal-chart.fullname".).Values.serviceAccount.name }}
{{- else }}
{{- default "default".Values.serviceAccount.name }}
{{- end }}
{{- end }}